### PR TITLE
linear and binary search

### PR DESCRIPTION
**Pull request by Danuragtiwari**

### CODE REVIEW

**Comment by Danuragtiwari** [comment]
please check and merge it!!

**Comment by Danuragtiwari** [comment]
@PratishShrivastava  check it!

**Review by PratishShrivastava — APPROVED** [review]

**Comment by PratishShrivastava** [comment]
@Danuragtiwari Thank you for contributing

**Comment by Danuragtiwari** [comment]
@PratishShrivastava you should have to label hacktoberfest-accepted in it

**Comment by Danuragtiwari** [comment]
thankx

**Pull request merged**
